### PR TITLE
update to localtime 

### PR DESCRIPTION
**Pull request by trentasis**
to allow update inventory multiple machines with same name

### CODE REVIEW

**Comment by jackburton79** [comment]
Thank you. What happens, though, if a machine sends an inventory multiple times ? This way it will be treated as different machines.
The nicer way to fix this would be to append the MAC address to the device id.

**Comment by trentasis** [comment]
ok,

I'll try to add mac.

Only one problem, when I recompile original or modifed version I can't send
inventory to http server, with local execution xml is correctly generated,
can you explain how to recompile correctly. With 5.4 we are using
./setup.sh and only error are with:
THINSTATION_PATH=`cat ../../THINSTATION_PATH`

. ../SET_ENV


Can you recompile with mac o give me some detail how to do?

Thanks

2015-09-29 15:20 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by jackburton79** [comment]
2015-09-29 15:54 GMT+02:00 trentasis <notifications@github.com>:

> ok,
>
> I'll try to add mac.
>
> Only one problem, when I recompile original or modifed version I can't send
> inventory to http server, with local execution xml is correctly generated,
> can you explain how to recompile correctly. With 5.4 we are using
> ./setup.sh and only error are with:
> THINSTATION_PATH=`cat ../../THINSTATION_PATH`
>
> . ../SET_ENV
>
>
> Can you recompile with mac o give me some detail how to do?
>
>
Hi,
We still haven't managed to test 5.4 yet.
When you specify the --server option, do you include the /ocsinventory part
in the url ?
Example: if your ocsinventory server name is "ocsinventory", the
commandline needs to be "ocsinventory-agent --server=
http://ocsinventory/ocsinventory

Hope this helps.
Bye!

**Comment by jackburton79** [comment]
I changed the device ID generation so it does not use the hostname. Can you test if it's working for your situation ?

**Comment by trentasis** [comment]
Thanks, great job, working in 2.2 and 5.4, and with 5.4 dmidecode package
installed.
It will be great to add support to inventory ram slots

Only change made with 5.4:
add dependency
dmidecode

compile with setup.sh but without thinstation_path and SET_ENV


Thanks for all

2015-09-30 20:57 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Pull request closed without merging**
